<h1>Therapy</h1>

<p><a href="#couples">Couples</a> | <a href="#child">Children and Adolescents</a> | <a href="#individual">Individuals</a></p>

<h2><a name="couples">Couples Therapy</a></h2>
<p>In my experience with couples I believe that there is one concept that embraces the heart of the work:  empathy.  Empathy is the capacity to understand and respond to the unique experiences of the other. Empathy's paradox is that this innate ability can be used for both helpful and hurtful purposes.</p>
<p>Empathy is an innate force, part of our biological inheritance, giving us energy, direction, and purpose in life.  Empathy is not a feeling or a sensation that suddenly washes over and engulfs us, but an intelligent, deeply respectful exploration of what lies beneath the surface of our world.  Helping us maintain a sense of balance and perspective in an ever-changing landscape, empathy teaches us how to flex and bend, letting go of our preconceptions and entering into our relationships with open hearts and open minds.</p>
<p>In couples therapy as we work through the issues we examine the relationship through a lens that explores commitment, individual and separate functioning, trust, individuation, intimacy, tolerance for ambiguity, capacity for self-observation, self-experience, and insight.  We examine the distribution of roles as they have developed in the relationship, the meaning and style of communication.  And as we explore together, we work toward a deeper development of empathy, reflected in the relationship as honesty, humility, acceptance, tolerance, gratitude, faith, hope, and forgiveness.</p>

<h2><a name="child">Child and Adolescent Therapy</a></h2>
<p>In my work with children and adolescents, I employ a variety of methods, including Gestalt therapy.  The main focus of this model is to help the child develop a strong sense of self and to creatively discover more healthy ways of being in the world.  The unique attributes of each child and his/her developmental level is honored and respected.</p>
<p>The sessions will be confidential, and it is advisable that you avoid questioning your child about the session unless your child voluntarily engages in discussion with you.  If something emerges in a session that I believe is of potential danger to self or others this confidentiality between me and your child will not apply.  I will be keeping you informed of the general direction of your child's therapy as we proceed.</p>
<p>The following is a basic descriptive outline of the therapeutic process, which is not linear.  I will be referring to this outline in ongoing evaluation and treatment focus for your child and will share this information with you.  Please feel free to ask me questions about the therapy process at any time, and keep me informed of significant events or changes in your child's life.</p>
<ol>
  <li><h3>Establishing the Therapeutic Relationship</h3>Your child and I will spend time getting to know one another.  This is a time for establishing boundaries and limits as well as building safety and trust.</li>
  <li><h3>Contact</h3>This relates to how a child presents him/herself to others and me in the world.  This also includes interaction with the environment.  Contact is established and evaluated at every session.  Resistance is honored and respected as a way for your child to cope with painful/threatening issues and material.</li>
  <li><h3>Contact Functions</h3>This includes developing and enhancing the senses, the body, breath, and voice.  Many activities are used to sharpen your child's awareness of his/her physical body and functions.</li>
  <li><h3>Self Support</h3>This area focuses on your child's ability to express himself/herself (i.e. opinions).  The child comes to know his/her own power.  The child develops his/her sense of mastery and learns when environmental support is needed.</li>
  <li><h3>Emotional Expression</h3>Self-expression and support precedes emotional expression.  Emotional expression work is conducted on five levels, starting with talking about feelings, to owning one's feelings, to learning skills to deal with owned feelings.  A variety of projective modalities are included for all of the areas of the therapeutic process, which include art, drawings, stories, puppets, sand tray, clay, and creative dramatics.</li>
  <li><h3>Self Nurturing Work</h3>This work is done after the child has owned his/her feelings.  The focus is to learn to accept and to take care of oneself and the younger inner child.  Children learn how to give nurturing messages to themselves.</li>
  <li><h3>Dealing with Process</h3>Here I deal more directly with the inappropriate behavior or ineffective coping mechanisms your child uses in unsuccessful attempts to meet needs.  Your child discovers and experiments with new tools that are more effective in meeting needs and learns how to obtain support from the environment.</li>
  <li><h3>Termination Process</h3>It is important to have a termination session with your child to bring closure to our work together for a particular period of time.  This also helps your child learn to deal with "goodbyes," and to let go before moving on.  Often issues may resurface at another developmental time, so termination is not necessarily final.  I provide your child with my business card at termination, as well as a symbol of our work, to reassure him/her that contact can be resumed when needed, or continued on a different level through periodic letters or "check-ins."</li>
  <li><h3>Family Work and Parent Education</h3>This is an essential part of the therapy and may take place periodically.  You may be asked to experiment with some new behaviors and/or tasks to facilitate your child's therapeutic process outside the confines of my office.  The purpose of these exercises is to help your child gain more self-awareness and to expand his/her repertoire of tools to deal more effectively with feelings.</li>
</ol>
<p>I appreciate the opportunity to work with you and your child, and look forward to a collaborative learning experience in our time together to facilitate your child's development of a strong sense of self, which will in turn help your child to make better contact with the world.</p>

<h2><a name="individual">Individual Therapy</a></h2>
<p>I practice a relational mode of individual psychotherapy.  From initial to final session I strive to establish and develop a therapeutic relationship, for this connection is pivotal to the treatment process.  I consider the work that we do together to be co-created, in that we share the responsibility to confront the barriers which may interfere with mental health and well-being.  Together we explore ways to promote self-growth and self-actualization.  In this way there is a mutual learning process fostered by our relationship.</p>

<p>In assessing an individual I want to understand the influence of formative experiences both past and present, including significant relationships.  We join to craft an approach to therapy that reflects the person’s unique developmental needs, challenges, and capabilities.</p>